### ISSUE TITLE
Prediction without a target column?

### ISSUE THREAD

**Issue by Treeboy2762** [cure-lab/DLinear#12]
Thanks for your sharing! Your paper was a pleasant read.

To my best understanding, all datasets have a target column as a 'dependent variable.' Is it possible to train the model on all columns instead with this inplementation? For example, a model trained with temperature & humidity will produce future temperature & humidity.

**Comment by mixiancmx** [comment]
Currently, it is not supported. We will update the code in later versions. For now, you might try to modify lines 54-55, lines 142-143, and 243-244 in 'data_provider/data_loader.py' and manually select the target column you are interested in.

**Comment by Treeboy2762** [comment]
Yes, I will modify dataloader myself for this. Have a nice day.

PS. I like your profile pic haha; it's my favorite emoticon
