### ISSUE TITLE
A question about the `freq` argument.

### ISSUE THREAD

**Issue by fuyw** [cure-lab/DLinear#13]
https://github.com/cure-lab/DLinear/blob/721ab5879ba72fe67fab0846ba2933c3074a0c53/data_provider/data_factory.py#L42

The argument `freq` is not set in any scripts, so we are using `args.freq = "h"` for all the dataset, including `ETTm1` and `ETTm2`.

And it seems all the baseline repos follow this setup.

**Comment by mixiancmx** [comment]
Hi, thanks for pointing out this problem. Yes, our scripts for transformer-based methods follow Autoformer's setup. They use freq="h" for ETTm1 and m2. DLinear doesn't use time features, so it is fine to set args.freq = "h" for all the dataset.

**Comment by fuyw** [comment]
Thank you.
