### ISSUE TITLE
Hi i have a question !

### ISSUE THREAD

**Issue by Yoontae6719** [cure-lab/DLinear#15]
![image](https://user-images.githubusercontent.com/87846187/184632607-3fd3ad1a-f289-4dc8-b2c6-bc28d8b6a69e.png)

Your research is very impressive. I wonder why you use the following code!

nn.Parameter((1/self.seq_len)*torch.ones([self.pred_len,self.seq_len]))

Why use the nn.parameter in linear module?
And why factor of nn.parameter (1/self.seq_len)*torch.ones([self.pred_len,self.I wonder if it is set to seq_len].

Thank you!

**Comment by mixiancmx** [comment]
To obtain a smooth weight with a clear pattern in visualization, we initialize the weights of the linear layers in DLinear as 1/L rather than random initialization. That is, we use the same weight for every forecasting time step in the look-back window at the start of training.
