### ISSUE TITLE
RuntimeError - Transformer

### ISSUE THREAD

**Issue by thainq07** [cure-lab/DLinear#6]
Hi!
When I ran script:
DLinear]scripts/EXP-LongForecasting/DLinear)/weather.sh
for base line model: Transformer

I got an error:
RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[16, 21, 338] to have 7 channels, but got 21 channels instead

If yes, can you tell me what the error is and how to fix it?

Thank so much!

**Comment by mixiancmx** [comment]
Hi, `scripts/EXP-LongForecasting/DLinear/weather.sh` is for the model 'DLinear' only. Some hyper parameter for transformer-based models is not listed in the script, such as enc_in, dec_in and c_out. These three hyper parameters should be set to 21 for transformer-based models on the weather dataset. If you want to run Transformer, you can find the corresponding script in `scripts/EXP-LongForecasting/Formers_Long.sh`
