### ISSUE TITLE
RunTime Error - Transformer

### ISSUE THREAD

**Issue by Vaiyani** [cure-lab/DLinear#7]
Hi, 

I have been trying to run Transformer for ETTh1.csv with feature = 's' (univariate predicts univariate) but gets the:
RuntimeError: Given groups=1, weight of size [512, 7, 3], expected input[32, 1, 98] to have 7 channels, but got 1 channels instead.

I did not find any example of feature = 'S' in the scripts. It was not part of the paper experiments I believe but do you know the arguments to make this mode run?

**Comment by mixiancmx** [comment]
Hi, please set enc_in, dec_in, c_out to 1. This means the input has 1 channel (variate). For example,
--feature S --enc_in 1 --dec_in 1 --c_out 1.

**Comment by Vaiyani** [comment]
Thanks, Yup I did that. Should have closed this before but thanks for re-affirming.
