### ISSUE TITLE
about the final results in the paper

### ISSUE THREAD

**Issue by super-shayan** [cure-lab/DLinear#8]
Hello, 

Thank you for open-sourcing the code. I wanted to ask a follow-up question, whether the final test results in the paper correspond to the averages across different random seeds or are the test results based on the minimum validation result across different seeds?

Thank you and looking forward to hearing from you

**Comment by mixiancmx** [comment]
Hi, all the result is under seed 2021. You can reproduce them by running the scripts we provide. In our code, we use the random seed set by Autoformer. They set it to 2021, so we follow them.

**Comment by super-shayan** [comment]
Thank you very much for your fast response! Much appreciated
